### ISSUE TITLE
Plugin not working for me in Sketch 52.2

### ISSUE THREAD

**Issue by daverobsonvb** [0la0/triangle-fields#2]
Hi there,

I've just downloaded and installed your plugin in Sketch 52.2, but unfortunately, it isn't working for me.

The plugin parameters popup appears and I can select the settings I want etc, but then when I click the 'Generare Triangles' button nothing happens, and I just get a message saying 'Selection must be a shape!' - even though I definitely have a shape selected.

After installing the plugin it immediately had an update, which I have run to no avail, and I have also tried this with all the different shapes and get the same issue each time.

**Comment by 0la0** [comment]
@daverobsonvb Thanks for the heads up!

It appears there were a few breaking changes to the API in Sketch 52 😬
I'll have a fix soon ... ⏳

**Comment by daverobsonvb** [comment]
@0la0 Ah ok, yes I figured it might be something due to the Sketch 52 upgrade that might have caused issues! That's great, look forward to giving it a go once you've had a chance to sort out a fix! 👍

**Comment by BethanyG** [comment]
Just chiming in with a "me too!" - and this isn't the only plug-in to be hosed by Sketch 52.x upgrades.  Chromatic-sketch & Blender have also stopped working for me....interestingly enough, they both fail at detecting shapes...so there was a major change to the API there.

Thank you for you plugin - and for your work on updates!  Really look forward to your fix!

**Comment by 0la0** [comment]
I updated the plugin to be compatible with Sketch 52. Thanks for the feedback!

**Comment by daverobsonvb** [comment]
Hi @0la0 I can't seem to get Sketch to update to version 2.0.0 for some reason? But I'm not sure if that's an issue with Sketch or with the update...?

**Comment by 0la0** [comment]
@daverobsonvb try uninstalling and reinstalling? I was having trouble with the sketch package manager. A fresh install should work.

**Comment by daverobsonvb** [comment]
@0la0 Hmm, have tried that a few times but it still isn't updating (or responding at all when I try and update) unfortunately!

**Comment by daverobsonvb** [comment]
@0la0 Unfortunately this still isn't working for me. I raised a support ticket with Sketch in case the issue is on Sketch's side, but their suggested solution for manually replacing the v1.0.1 instance already installed with your latest version from here on Github didn't work either, as the newly downloaded version still installs as v1.0.1 and immediately suggests updating to v2.0.0 (which again doesn't respond).

**Comment by BethanyG** [comment]
Hi @daverobsonvb - 

FWIW, I deleted the `triangle-field.sketchplugin` file from my plugins folder and re-installed it manually  from a fresh download from this repo and that worked for me.  I'm on a Mac running High Sierra, and I'm using Sketch 52.4.  *However*, I did find that `manifest.json` had an incorrect version number (1.0.1 instead of 2.0.0) - so the update nagger for Sketch kept coming on and wrecking havoc.  So I opened up `manafest.json` in a code editor and changed the version field to 2.0.0 - and that fixed my issues.

I did the following:
1. Go to the **manage plugins** menu, and click on the gear icon in the bottom left corner.  
2. Select **Reveal Plugins Folder** -- that should take you to where the plugin files are located.  
3. Find `triangle-field.sketchplugin`, and open that in Atom or Sublime or VS Code, etc.    
4. Under the `Contents` folder, find the `Sketch` folder.  Inside the `Sketch` folder, you'll find `manafest.json`.  
5. Once `manafest.json` is open, change the **version** field to 2.0.0.  
6. Save the file, and quit and re-open Sketch.

**Comment by 0la0** [comment]
Amazing! Thank you @BethanyG and @daverobsonvb 
I've released v2.0.1 (hopefully the version bumps are correct).
🤞Let me know if it works 🤞

**Comment by daverobsonvb** [comment]
@BethanyG Thanks very much, I followed your process and it's now working for me!

@0la0 After using Bethany G's method I was able to get v2.0.0 working, but still couldn't update to v2.0.1 within Sketch itself (despite Sketch offering the update). Had to download the latest version from this repo and then open the `triangle-field.sketchplugin` file in Finder which then replaced v2.0.0 and successfully updated the plugin in Sketch.

Thanks for your work on this, glad to be able to use this plugin now! :)
